#!/bin/bash
#卸载程序后，删除驱动的安装文件
#rm /opt/devices/eGTouch_v2.5.5814.L-x -Rf
#rm /etc/rcS.d/S99eGTouch

#手动安装驱动模式，需要清理/etc/rc.local和/etc/modprobe.d/blacklist.conf

sed -i '/\/usr\/bin\/eGTouchD/d' /etc/rc.local
sed -i '/blacklist usbtouchscreen/d' /etc/modprobe.d/blacklist.conf
