#!/bin/sh

export LANGUAGE=C

if [ "$( ps -A | grep ucloner_gui)" ] ; then
    zenity --title="Error" --error --text="There is already a UCloner running!"
    exit 1
fi

cd ./program
exec gksu ./ucloner_gui.py &> /dev/null


